version: '3.5'
services:
  zookeeper:
    image: zookeeper:latest
    networks:
      - locking-poc-zookeeper
    ports:
      - "2181:2181"
      - "8080:8080"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      TZ: America/Toronto

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: caik/kotlin-locking-poc-zookeeper-app:latest
    networks:
      - locking-poc-zookeeper
    environment:
      APP: zookeeper
      ZOOKEEPER_HOST: zookeeper
      JVM_ARGS: '--add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED'
      TZ: America/Toronto
    deploy:
      replicas: 2

networks:
  locking-poc-zookeeper: null